 name: gitartwork
 on: 
   push:
 jobs:
   build:
     name: gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: jasineri/gitartwork@v1
         with:
            user_name: m4ndil
            text: m4ndil
       - uses: jasineri/simple-push-action@v1
